In [183]:
model=[
    [7,0,0,8,0,0,1,2,0],
    [0,9,0,0,4,0,0,0,0],
    [0,0,0,0,0,0,0,0,3],
    [1,0,0,2,0,0,5,7,0],
    [0,0,0,0,0,0,0,6,0], 
    [0,0,2,0,0,8,0,0,0],
    [0,7,0,0,0,9,3,5,0],
    [0,0,0,5,0,0,0,0,6],
    [3,0,0,0,0,0,0,0,8]
]

import numpy as np


In [222]:
def rest(rows,cols,blocks):
    r = []
    for i in range(1,10):
        if (i not in rows) and (i not in cols) and (i not in blocks):
            r.append(i)
    return r
def fill1(model2,stack):
    r = None
    rmin = 10
    for rowi in range(9):    
        for coli in range(9):
            if model2[rowi][coli] == 0:
                rows = model2[rowi]
                cols = model2[:,coli]
                blocks = model2[rowi//3*3:rowi//3*3+3,coli//3*3:coli//3*3+3] 
                blank = rest(rows,cols,blocks)
                #print(rowi, coli, rows, cols, blocks, blank)
                if len(blank)==1:
                    model2[rowi][coli] = blank[0]
                    #print(rowi,coli)
                    return True
                if len(blank)<rmin:
                    rmin = len(blank)
                    r = [rowi,coli,blank]
    if(r is not None) and (len(r[2]) > 0) :#大于1可以么？
        for i in range(1, len(r[2])): #range (1,4) 1，2，3
            newmodel2 = np.copy(model2)
            newmodel2[r[0]][r[1]]= r[2][i]
            stack.append(newmodel2)
        #print(r[0], r[1], r[2], model2)
        
        model2[r[0]][r[1]]=r[2][0]
        return True
    return False


In [217]:
a=np.array([1,2])
print(a)
b = a[:]
b[0] = 2
print(a)

[1 2]
[2 2]


In [221]:
stack =[]
model2 = np.array([
    [7,0,0,8,0,0,1,2,0],
    [0,9,0,0,4,0,0,0,0],
    [0,0,0,0,0,0,0,0,3],
    [1,0,0,2,0,0,5,7,0],
    [0,0,0,0,0,0,0,6,0], 
    [0,0,2,0,0,8,0,0,0],
    [0,7,0,0,0,9,3,5,0],
    [0,0,0,5,0,0,0,0,6],
    [3,0,0,0,0,0,0,0,8]
])
while (fill1(model2, stack)):
    continue
print(stack)

1 7
2 7
2 6
3 8
5 6
5 8
4 8
4 6
5 7
[array([[7, 0, 0, 8, 0, 0, 1, 2, 0],
       [0, 9, 0, 0, 4, 0, 7, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3],
       [1, 0, 0, 2, 0, 0, 5, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 2, 0, 0, 8, 0, 0, 0],
       [0, 7, 0, 0, 0, 9, 3, 5, 0],
       [0, 0, 0, 5, 0, 0, 0, 0, 6],
       [3, 0, 0, 0, 0, 0, 0, 0, 8]]), array([[7, 0, 0, 8, 0, 0, 1, 2, 0],
       [5, 9, 0, 0, 4, 0, 6, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3],
       [1, 0, 0, 2, 0, 0, 5, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 2, 0, 0, 8, 0, 0, 0],
       [0, 7, 0, 0, 0, 9, 3, 5, 0],
       [0, 0, 0, 5, 0, 0, 0, 0, 6],
       [3, 0, 0, 0, 0, 0, 0, 0, 8]]), array([[7, 0, 0, 8, 0, 0, 1, 2, 0],
       [2, 9, 0, 0, 4, 0, 6, 8, 7],
       [0, 0, 0, 0, 0, 0, 0, 0, 3],
       [1, 0, 0, 2, 0, 0, 5, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 2, 0, 0, 8, 0, 0, 0],
       [0, 7, 0, 0, 0, 9, 3, 5, 0],
       [0, 0, 0, 5, 0, 0, 0, 0, 6],
       [3, 0, 0, 0, 0, 

In [224]:

stack =[]
model2 = np.array(model)
ii = 1
while (fill1(model2, stack)):
    continue
while ((model2 == 0).any()):#any是对矩阵判断是否有某个数字，只要有一个true则返回true
    ii +=1
    model2 = stack[-1]
    stack = stack[:-1]
    #print("back", len(stack), model2)
    while (fill1(model2,stack)):
        continue
print("total",ii)
print(model2)

total 78
[[7 3 4 8 9 6 1 2 5]
 [2 9 5 3 4 1 6 8 7]
 [6 1 8 7 5 2 9 4 3]
 [1 8 3 2 6 4 5 7 9]
 [9 4 7 1 3 5 8 6 2]
 [5 6 2 9 7 8 4 3 1]
 [8 7 1 6 2 9 3 5 4]
 [4 2 9 5 8 3 7 1 6]
 [3 5 6 4 1 7 2 9 8]]


In [115]:
AAAA = [1,2,3,4,5,6]
AAAA = AAAA[-1]
AAAA

6